version: "3.9"
services:
  db:
    image: postgres:11
    container_name: postgres-11-space-db
    restart: always
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=space-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ROOT_HOST='%'
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - lfpo-network

  space-flight-news:
    image: lfpo2005/space-flight-news
    build: .
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/space-db
      SPRING.DATASOURCE.URL.USERNAME: postgres
      SPRING.DATASOURCE.URL.PASSWORD: postgres
    ports:
      - 8081:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - lfpo-network

networks:
  lfpo-network:
    driver: bridge