server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/space-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

#space:
#  api:
#    apiUrl: https://api.spaceflightnewsapi.net/v3

application:
  articles:
    by-date-uri: https://api.spaceflightnewsapi.net/v3/articles?publishedAt_gt=%s&_limit=100
    batch-uri: https://api.spaceflightnewsapi.net/v3/articles?_start=%d&_limit=${application.articles.itens-per-page-import}
    count-uri: https://api.spaceflightnewsapi.net/v3/articles/count
    itens-per-page-import: 200
    itens-to-import: 200
    import:
      daily:
        cron-expression: "0 0 22 * * ?"
      active: false
